version: '2' # required to adjust maintainability checks
checks:
    method-complexity:
        config:
            threshold: 10 # default is 5

# Ref: https://docs.codeclimate.com/docs/advanced-configuration
